### ISSUE TITLE
Out of memory error when activating the php7-fix branch

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/cart66pro#1]
I get this error when activating the php7-fix branch on my local MAMP site with 512M of memory set in wp-config:

PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /wp-content/plugins/cart66/models/Cart66CartWidget.php on line 7

**Comment by michaeltorbert** [comment]
This should be fixed now

**Comment by wpsmort** [comment]
This is confirmed fixed.
